server:
  port: 80
spring:
  datasource:
    #���ݿ�����������
    username: test
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crm?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
  freemarker:
    #ָ��HttpServletRequest�������Ƿ���Ը���controller��model��ͬ����
    allow-request-override: false
    #req����request
    request-context-attribute: req
    #��׺��freemarkerĬ�Ϻ�׺Ϊ.ftl����Ȼ��Ҳ���Ըĳ��Լ�ϰ�ߵ�.html
    suffix: .html

    #������Ӧ����������
    content-type: text/html;charset=utf-8
    #�Ƿ�����mvcʹ��freemarker
    enabled: true
    #�Ƿ���template caching
    cache: false
    #�趨ģ��ļ���·��������Զ��ŷָ���Ĭ��: [��classpath:/templates/��]
    template-loader-path: classpath:/templates/
    #�趨Template�ı���
    charset: UTF-8
#��ʾ��־
logging:
  level:
    com.zxy.code.mapper: debug